["protostar.config"]
protostar_version = "0.2.5"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src", "tests"]

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/tempest.cairo",
]
router = [
   "src/router.cairo"
]
factory = [
   "src/factory.cairo"
]


["protostar.test"]
target = ["tests"]
